### ISSUE TITLE
It creates the 1_output file but doesn't seem to do anything else

### ISSUE THREAD

**Issue by MotorCityCobra** [Tyrannosaurus1234/GetFaces#2]
I'm on Ubuntu 16.04
I've used the face_recognition and cv2 packages in this same env I'm trying your script in without incident.

$ python3.5 getfaces.py -i </PATH/TO/JPG/FOR/FR/TO/LEARN.jpg> -v </PATH/TO/AN/MP4/FILE/VID.mp4>

Creates only an empty folder after completing.  
Displays...  

Target filename: </PATH/TO/JPG/FOR/FR/TO/LEARN.jpg>.
Video filename: </PATH/TO/AN/MP4/FILE/VID.mp4>.
Tolerance: 0.6.
Using OpenCL: True.
Output directory: /PATH/MY/JPG/IS/IN/1_output.
Frame Width: 0.0, Height: 0.0.
$

**Comment by ghost** [comment]
Did you check the opencv Version? I used the same I use for FaceSwap, but you need a newer one. I had this problem, and solved it this way:

pip3 uninstall opencv-python 
pip3 install opencv-python

I use virtualenv now.

**Comment by MotorCityCobra** [comment]
That was it.
It works now.
Thank you for finding my oversight.
