### ISSUE TITLE
Don't cut the face, just export the Frame

### ISSUE THREAD

**Issue by ghost** [Tyrannosaurus1234/GetFaces#3]
Is it possible to create an option to just export the complete frame not only the face? I'd like to do the extraction with faceswap.

That would be great. I'm just a starter with python, so I can't do it myself - yet :-)

Thanks!

**Comment by Tyrannosaurus1234** [comment]
Implemented, use "-c false" launch argument to export full frames. Not sure why you would want to do this, considering the whole point of this script is to avoid the faceswap extract script picking up wrong faces, but I've added it anyways. I would recommend just running the extract script on the (cropped) frames this script spits out, but if you want the full frames, here you go.

**Comment by ghost** [comment]
Thanks! I really like your video export feature, but everything else I do with faceswap in one step. Using the best of both worlds. Thanks for the fast feature add! :-)
